### PR TITLE
Context best-practices

### PR DESCRIPTION
**Pull request by gomorizsolt**
Looking for ideas..
- low-level examples if possible
- rephrase sentences if necessary

### CODE REVIEW

**Comment by thisismydesign** [comment]
Found these articles you mentioned the last time quite useful. Probably worth a mention in the guides as well:
- https://kentcdodds.com/blog/prop-drilling

**Comment by thisismydesign** [comment]
Why are contexts an overkill though?

**Comment by gomorizsolt** [comment]
Forget the proposal above, it seems it's indeed one of the best-practices of using contexts.

> Use React's Context API for things that are truly necessary deep in the react tree. They don't have to be things you need everywhere in the application (you can render a provider anywhere in the app). This can really help avoid some issues with prop drilling. It's been noted that context is kinda taking us back to the days of global variables. The difference is that because of the way the API was designed, you can still statically find the source of the context as well as any consumers with relative ease.

Source: https://kentcdodds.com/blog/prop-drilling

**Comment by thisismydesign** [comment]
Closing in favor of https://github.com/c-hive/guides/commit/ca945f67b544921e5b1573d06ada261f8c90ecf4 and https://github.com/c-hive/basics/issues/8

Thanks for gathering use cases in this PR!

**Pull request closed without merging**
